# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'The Car Shop' do
  use_frameworks!
  
  pod 'PKHUD'
  pod 'Alamofire', '4.9'
  pod 'ObjectMapper'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireObjectMapper', '~> 5.2'

  
end
